# Generated/updated by neoforge-26.2-converter
# Target: Minecraft 26.2 / NeoForge 26.2.0.32-beta

# Gradle
org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment - https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.32-beta

## Mod Properties
mod_id=pchaoskit
mod_name=PChaosKit
mod_license=Not specified
mod_version=26.2.0
mod_group_id=net.mcreator.pchaoskit
mod_authors=MCreator
mod_description=PChaosKit for Minecraft 26.2
mod_credits=Created using mod maker MCreator - https://mcreator.net/about
mod_display_url=https://mcreator.net
